project:
  type: website
  output-dir: docs

website:
  title: "Thomas Price"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Visualization 
        href: DataViz.qmd
        menu:
          - href: tidygas.qmd
            text: US Gas Prices
          - href: tidy2.qmd
            text: TidyTuesday 2

about:
  template: jolla
  image: images/Img_123.jpeg
  image-shape: round
  image-width: 17em
  links:
    - text: LinkedIn
      href: https://www.linkedin.com/in/thomas-price-tprice/
    - text: GitHub
      href: https://github.com/thomasprice151151
    - text: Email
      href: mailto:tprice@students.pitzer.edu

format:
  html:
    theme: mint
    toc: true


