project:
  type: website
  output-dir: docs

website:
  title: "Thomas Price"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Visualization 
        menu:
          - href: tidygas.qmd
            text: US Gas Prices
          - href: billboard_t100.qmd
            text: Billboard Top 100 
          - href: Proj2.qmd
            text: Analysis of Obama's Tweets (Proj2)
            

format:
  html:
    theme: mint
    toc: true
